# Generated by Django 3.0.8 on 2020-07-06 22:19
import os
import json

from django.db import migrations
from django.utils.text import slugify


STATES_DATA_PATH = os.path.join(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__)
)), 'states_data')


def add_data(apps, schema_editor):
    State = apps.get_model('states', 'State')
    LGA = apps.get_model('states', 'LocalGovernmentArea')

    with open(os.path.join(STATES_DATA_PATH, 'states.json'), 'r') as json_file:
        states = json.loads(json_file.read())

    for state in states:
        name = state['name'].strip().lower()
        capital = state['capital'].strip().lower()
        slug = slugify(state['name'].strip())
        created_state = State.objects.create(
            name=name, capital=capital, slug=slug)
        for lga in state['lgas']:
            name = lga.strip().lower()
            LGA.objects.create(name=name, state=created_state)


def remove_data(apps, schema_editor):
    State = apps.get_model('states', 'State')
    LGA = apps.get_model('states', 'LocalGovernmentArea')
    State.objects.all().delete()
    LGA.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            add_data,
            remove_data
        )
    ]
